---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wateqwvu/zspec.dev/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R data_crunching $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp feed.xml $DEPLOYPATH

